const config = {
  dict: {
    'pt-br': {
      'Sign In': 'Entrar',
      'Sign in': 'Entrar',
      'Sign Up': 'Registrar',
      'Sign Out': 'Sair',
      'Confirm Sign Up': 'Confirmar Registro',
      Username: 'Usuário',
      Password: 'Senha',
      'Forgot Password': 'Esqueceu sua senha?!',
      'Change Password': 'Trocar senha',
      'Create Account': 'Criar conta',
      'Create account': 'Criar conta',
      'Create a new account': 'Criar nova conta',
      'New Password': 'Nova senha',
      'Phone Number': 'Telefone',
      'Sign in with your': 'Entre com',
      'Username cannot be empty': 'Usuario não pode estar vazio',
      'Enter your username': 'Digite seu usuário',
      'Enter your password': 'Digite sua senha',
      'No account? ': 'Ainda não tem conta? ',
      'Sign in to your account': 'Entrar na sua conta',
      'Reset password': 'Recuperar senha',
      'Forget your password? ': 'Esqueceu a senha? ',
      'Have an account? ': 'Já tem uma conta? ',
      'Confirmation Code': 'Código de Confirmação ',
      'Lost your code? ': 'Esqueceu o código? ',
      'Resend Code': 'Reenviar código',
      'Enter your code': 'Digite o seu código',
      'Back to Sign In': 'Voltar ao Login',
      Confirm: 'Confirmar',
      'Reset your password': 'Recuperar sua senha',
      'Send Code': 'Enviar código',
      'User already exists': 'Usuário já existe.',
      Name: 'Nome',
      Nickname: 'Apelido',
      Change: 'Alterar',
    },
  },
};

export default config;
